version: '3.8'

services:
  influxdb:
    image: influxdb:1.8.10
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=web3-pi-password
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-influxdb-flux-datasource
      - GF_AUTH_BASIC_ENABLED=true
      - GF_SECURITY_DISABLE_BRUTE_FORCE_LOGIN_PROTECTION=true

    volumes:
      - influxdb_data:/var/lib/influxdb

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=web3-pi-password
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-influxdb-flux-datasource
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards

    depends_on:
      - influxdb

volumes:
  influxdb_data:
  grafana_data:
