{
 "title": "Web3 Pi Transaction Firewall Dashboard",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Total Rpc call",
   "type": "stat",
   "description": "Total number of RPC calls",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Total RPC Calls",
     "query": "SELECT count(\"jsonRpcId\") FROM \"tx_firewall_metrics\" WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "Forwarded Call (no validation)",
   "type": "stat",
   "description": "Number of forwarded RPC calls",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Forwarded Calls",
     "query": "SELECT count(\"jsonRpcId\") FROM \"tx_firewall_metrics\" WHERE $timeFilter AND \"result\" = 'forwarded'"
    }
   ]
  },
  {
   "title": "Total Transactions",
   "type": "stat",
   "description": "Statistical Indicators for Transactions",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Total",
     "query": "SELECT count(\"txId\") FROM \"tx_firewall_metrics\" WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "Rejected Transactions",
   "type": "stat",
   "description": "Number of rejected transactions",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Rejected",
     "query": "SELECT count(\"jsonRpcId\") FROM \"tx_firewall_metrics\" WHERE $timeFilter AND \"result\" = 'rejected'"
    }
   ]
  },
  {
   "title": "Accepted Transactions",
   "type": "stat",
   "description": "Number of accepted transactions",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Forwarded",
     "query": "SELECT count(\"jsonRpcId\") FROM \"tx_firewall_metrics\" WHERE $timeFilter AND \"result\" = 'accepted'"
    }
   ]
  },
  {
   "title": "Errored Transactions",
   "type": "stat",
   "description": "Number of errored transactions",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Errored",
     "query": "SELECT count(\"jsonRpcId\") FROM \"tx_firewall_metrics\" WHERE $timeFilter AND \"result\" = 'error' GROUP BY time($__interval) fill(0)"
    }
   ]
  },
  {
   "title": "Transactions by Validation Status",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_result",
     "query": "SELECT count(\"jsonRpcId\") FROM \"tx_firewall_metrics\" WHERE $timeFilter  AND \"result\" != 'forwarded' GROUP BY time($__interval), \"result\" fill(null)"
    }
   ]
  },
  {
   "title": "RPC Calls by Method Type",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_jsonRpcMethod",
     "query": "SELECT count(\"jsonRpcId\") FROM \"tx_firewall_metrics\" WHERE $timeFilter GROUP BY time($__interval), \"jsonRpcMethod\" fill(null)"
    }
   ]
  },
  {
   "title": "Transaction Breakdown by Status",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "$tag_result",
     "query": "SELECT count(\"jsonRpcId\") FROM \"tx_firewall_metrics\" WHERE $timeFilter AND \"result\" != 'forwarded' GROUP BY \"result\""
    }
   ]
  },
  {
   "title": "RPC Methods Distribution",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "$tag_jsonRpcMethod",
     "query": "SELECT count(\"jsonRpcId\") FROM \"tx_firewall_metrics\" WHERE $timeFilter GROUP BY \"jsonRpcMethod\""
    }
   ]
  },
  {
   "title": "Recent Transactions",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "query": "SELECT time, txId, \"from\", labelFrom, \"to\", labelTo, txType, value, result FROM \"tx_firewall_metrics\" WHERE $timeFilter AND jsonRpcMethod = 'eth_sendRawTransaction' ORDER BY time DESC LIMIT 30"
    }
   ]
  }
 ]
}